require.config({
	paths:{
		"jquery":"jquery-1.11.3",
		"startMove":"startMove",
		"qstartMove":"qstartMove",
		"top":"top",
		"shousuo":"shousuokuang",
		"lunbo":"lunbo",
		"daojishi":"daojishi",
		"temai":"temai",
		"loucheng":"loucheng",
		"daren":"daren",
		"cart":"cart",
		"louti":"louti"
	}
})
require(["qstartMove","jquery","startMove","top","shousuo","lunbo","daojishi","temai","loucheng","daren","cart","louti"],function(qstartMove,jquery,startMove,top,shousuo,lunbo,daojishi,temai,loucheng,daren,cart,louti){
	top();
	lunbo();
	daojishi();
	temai();
	loucheng();
	daren();
	cart();
	louti();
})